### ISSUE TITLE
Admin ,unable to deploy the app , it is showing item could not be created

### ISSUE THREAD

**Issue by SaiHarsha12** [Aadhi000/File-To-Link#1]
![Screenshot_2022-05-18-17-57-13-603_com android chrome](https://user-images.githubusercontent.com/88876604/169038778-b74102c0-a3d9-4c72-b42f-1d2aed78aa2d.jpg)

**Comment by Aadhi000** [comment]
Bro First Fork the repo then change the deploy link with your new forked link then deploy

**Comment by SaiHarsha12** [comment]
Bro i forked the link and also changed everything, even though it's coming
like this, send me pull request si that I can deploy

**Comment by SaiHarsha12** [comment]
Reply bro!!
